alias: "Phone Voice Notification: News Flash"
description: "Announces news via TTS when home, during day hours, and not on a call."

triggers:
  - trigger: state
    entity_id: binary_sensor.news_sensor
    from: "off"
    to: "on"

conditions:
  # Ensure you are home
  - condition: state
    entity_id: person.your_name # <--- Change to your person entity
    state: "home"
  
  # Ensure you are not currently on a phone call (to avoid ear-blasting)
  - condition: state
    entity_id: sensor.your_phone_id_phone_state # <--- Change to your phone state sensor
    state: "idle"
    
  # Only during waking hours
  - condition: time
    after: "06:50:00"
    before: "21:00:00"

actions:
  # 1. Increase the alarm_stream level to max
  - action: notify.mobile_app_your_phone_id # <--- Change to your mobile_app notify service
    data:
      message: "command_volume_level"
      data:
        media_stream: "alarm_stream"
        command: 100

  # 2. Wait for the system to register the volume change
  - delay:
      seconds: 1

  # 3. Send the TTS notification fetching data from the sensor attribute
  - action: notify.mobile_app_your_phone_id # <--- Change to your mobile_app notify service
    data:
      message: "TTS"
      data:
        tts_text: "{{ state_attr('binary_sensor.news_sensor','msg1') }}"
        media_stream: "alarm_stream"
        ttl: 0
        priority: high

  # 4. Wait for the announcement to finish (adjust if news flashes are long)
  - delay:
      seconds: 10

  # 5. Restore the alarm level to a normal background level (e.g., 10%)
  - action: notify.mobile_app_your_phone_id # <--- Change to your mobile_app notify service
    data:
      message: "command_volume_level"
      data:
        media_stream: "alarm_stream"
        command: 10

mode: single
