alias: Radiator
description: ""
triggers:
  - entity_id:
      - sensor.radiator_low
    from: "False"
    to: "True"
    id: below
    trigger: state
  - entity_id:
      - sensor.radiator_high
    from: "False"
    to: "True"
    id: above
    trigger: state
  - at: "06:31:00"
    id: "OFF"
    trigger: time
  - at: "06:35:00"
    id: "OFF"
    trigger: time
  - at: "06:45:00"
    id: "OFF"
    trigger: time
conditions:
  - condition: state
    entity_id: input_select.home_travel
    state: home
actions:
  - if:
      - condition: trigger
        id:
          - below
      - condition: state
        entity_id: switch.kids_socket
        state: "off"
      - condition: template
        value_template: |2

            {% set current_time = now().time() %}
            {% set start_time = '19:00:00'.split(':') | map('int') | list %}
            {% set end_time = '06:30:00'.split(':') | map('int') | list %}
            {% set in_time_range = current_time >= current_time.replace(hour=start_time[0], minute=start_time[1], second=start_time[2]) or current_time <= current_time.replace(hour=end_time[0], minute=end_time[1], second=end_time[2]) %}
            {% set in_months = now().month in [12, 1, 2, 3, 4] %}
            {{ in_time_range and in_months }}
    then:
      - target:
          entity_id: switch.kids_socket
        data: {}
        action: switch.turn_on
      - data:
          message: 拽转 转 专专, 转 砖专 拽专
          title: "注 转  专注 "
          target: -123456
        action: telegram_bot.send_message
      - action: notify.greenapi
        data:
          message:  拽转 转 专专 专 拽专  砖注转 砖
          target: 123456@g.us
  - if:
      - condition: trigger
        id:
          - above
      - condition: state
        entity_id: switch.kids_socket
        state: "on"
    then:
      - target:
          entity_id:
            - switch.kids_socket
        data: {}
        action: switch.turn_off
      - data:
          title:   驻拽
          message: 住专转 转 专专, 拽 砖 砖转 转拽专专
          target: -123456
        action: telegram_bot.send_message
      - action: notify.greenapi
        data:
          message:  "转 转  ( 专  砖注转 砖 )."
          target: 123456@g.us
  - if:
      - condition: trigger
        id:
          - "OFF"
      - condition: state
        entity_id: switch.kids_socket
        state: "on"
    then:
      - target:
          entity_id: switch.kids_socket
        data: {}
        action: switch.turn_off
mode: single
