alias: Boiler_Daily_under26
description: "Smart Boiler Logic with Safety Fail-safes"
mode: restart

trigger:
  # 1. 驻注 转  (驻 砖 砖注)
  - platform: template
    value_template: "{{ now().strftime('%H:%M') == states('sensor.boiler_trigger_time') }}"
    id: Triggered

  # 2. 砖注转   (转 - Hard Stop)
  - platform: time
    at: "18:32:00"
    id: Closer

  # 3.  转转 转专 (注 60 注转)
  # 拽 砖转 注 (-3 砖注转 专转)
  - platform: template
    value_template: |2-
      {% set temp = states('sensor.boiler_temp_temperature') | float(0) %}
      {% set last_changed = states.sensor.boiler_temp_temperature.last_changed %}
      {% set hours_since_update = (now() - last_changed).total_seconds() / 3600 %}
      {{ temp > 60 and hours_since_update < 3 }}
    id: Hot_Enough

condition:
  # 转  -  转 转  砖 专祝
  - condition: state
    entity_id: input_select.home_travel
    state: home
  - condition: template
    value_template: "{{ now().month in [10, 11, 12, 1, 2, 3, 4] }}"

action:
  # --- 转专砖 1: 拽 转 ---
  - if:
      - condition: trigger
        id: Triggered
      - condition: template
        value_template: "{{ is_state('sensor.boiler_turn', 'Yes') }}"
      # 转  爪   -global  驻砖专  转 驻注 砖 拽
      - condition: state
        entity_id: switch.boiler
        state: "off"
    then:
      - service: switch.turn_on
        target:
          entity_id: switch.boiler
      
      # 注转 转
      - service: notify.greenapi
        data:
          title: "ヰ   "
          message: " 拽转 转  砖 {{ states('sensor.boiler_time') | int(30) }} 拽转"
          target: 123456789@g.us
      - service: telegram_bot.send_message
        data:
          title: "Smart Boiler"
          message: " 拽转 转  砖 {{ states('sensor.boiler_time') | int(30) }} 拽转"
          target: -10012345678
      
      # 专 拽转 (TTS) - 转
      - service: media_player.volume_set
        target:
          entity_id: media_player.living_room_speaker
        data:
          volume_level: 0.7
      - service: tts.speak
        target:
          entity_id: tts.google_translate_iw_co_il
        data:
          media_player_entity_id: media_player.living_room_speaker
          message: "转 砖 拽专 , 拽转 转  -{{ states('sensor.boiler_time') | int(30) }} 拽转"
      
      # 转  
      - delay: "{{ (states('sensor.boiler_time') | int(30) * 60) }}"
      
      #  住
      - service: switch.turn_off
        target:
          entity_id: switch.boiler
      
      # 注转 住
      - service: media_player.volume_set
        target:
          entity_id: media_player.living_room_speaker
        data:
          volume_level: 0.78
      - service: tts.speak
        target:
          entity_id: tts.google_translate_iw_co_il
        data:
          media_player_entity_id: media_player.living_room_speaker
          message: "转 转 ,   转拽"
      - service: telegram_bot.send_message
        data:
          title: "Smart Boiler"
          message: " 转 转 "
          target: -10012345678
      - service: notify.greenapi
        data:
          title: "ヰ   "
          message: " 转 转 "
          target: 123456789@g.us

  # --- 转专砖 2: 砖注转  (Failsafe) ---
  - if:
      - condition: trigger
        id: Closer
      - condition: state
        entity_id: switch.boiler
        state: "on"
    then:
      - service: switch.turn_off
        target:
          entity_id: switch.boiler
      - service: notify.greenapi
        data:
          title: "ヰ Error"
          message: "爪  住 , 住专 转  (Failsafe)."
          target: 123456789@g.us

  # --- 转专砖 3: 转  (Overheat) ---
  - if:
      - condition: trigger
        id: Hot_Enough
      - condition: state
        entity_id: switch.boiler
        state: "on"
    then:
      - service: notify.greenapi
        data:
          title: "ヰ Max Temp"
          message: "驻专专 注 拽住 (60掳),  砖专 注 ."
          target: 123456789@g.us
      - service: switch.turn_off
        target:
          entity_id: switch.boiler
