alias: Boiler - ON Logic (Full)
description: 拽 转 , 砖 转专转 专 专拽
triggers:
  - trigger: template
    value_template: "{{ now().strftime('%H:%M') == states('sensor.boiler_trigger_time') }}"
conditions:
  - condition: state
    entity_id: input_select.home_travel
    state: home
  - condition: template
    value_template: "{{ now().month in [10, 11, 12, 1, 2, 3, 4] }}"
  - condition: state
    entity_id: switch.boiler
    state: "off"
  - condition: state
    entity_id: sensor.boiler_turn
    state: "Yes"
actions:
  - action: switch.turn_on
    target:
      entity_id: switch.boiler
    data: {}
  - action: notify.greenapi
    data:
      title: ヰ   
      message:  拽转 转  砖 {{ states('sensor.boiler_time') | int(30) }} 拽转
      target: 123456789@g.us
  - action: telegram_bot.send_message
    data:
      title:   
      message:  拽转 转  砖 {{ states('sensor.boiler_time') | int(30) }} 拽转
      target: -12345678
  - action: media_player.volume_set
    target:
      entity_id: media_player.living_room_speaker
    data:
      volume_level: 0.7
  - action: tts.speak
    target:
      entity_id: tts.google_translate_iw_co_il
    data:
      media_player_entity_id: media_player.living_room_speaker
      message: >-
        转 砖 拽专 , 拽转 转  -{{ states('sensor.boiler_time') |
        int(30) }} 拽转
mode: single
