alias: "System: Reset Boiler Flag"
description: ""
triggers:
  - trigger: state
    entity_id: switch.boiler
    to: "off"
actions:
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.boiler_auto_mode
