alias: Tv_silence_Optimized_Final
description: Limit TV volume between 05:00 and 07:00
mode: restart
triggers:
  - entity_id: media_player.lg_webos_tv_oled65_xxx
    attribute: volume_level
    trigger: state
  - entity_id: media_player.lg_webos_tv_oled65_xxx
    to: "on"
    trigger: state
  - at: "05:00:00"
    trigger: time
conditions:
  - condition: time
    after: "04:59:00"
    before: "07:00:00"
  - condition: numeric_state
    entity_id: media_player.lg_webos_tv_oled65_xxx
    attribute: volume_level
    above: 0.1
actions:
  - target:
      entity_id: media_player.lg_webos_tv_oled65_xxx
    data:
      volume_level: 0.1
    action: media_player.volume_set
